services:
  customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=CS@#123456#!
    ports:
      - "14339:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sql_data:
    name: sql_data
  rabbitmq_data: