//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره حساب وارد شده معتبر نمی باشد.
        /// </summary>
        public static string BankAccountNumberFormatIsNotValid {
            get {
                return ResourceManager.GetString("BankAccountNumberFormatIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب نمیتواند شامل حروف باشد.
        /// </summary>
        public static string CannotContainNonDigitException {
            get {
                return ResourceManager.GetString("CannotContainNonDigitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده یافت نشد.
        /// </summary>
        public static string DataNotFoundException {
            get {
                return ResourceManager.GetString("DataNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد اجباری می باشد.
        /// </summary>
        public static string DateOfBirthDateIsRequiredException {
            get {
                return ResourceManager.GetString("DateOfBirthDateIsRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ایمیل وارد شده معتبر نمی باشد.
        /// </summary>
        public static string EmailFormatIsNotValidException {
            get {
                return ResourceManager.GetString("EmailFormatIsNotValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده تکراری می باشد.
        /// </summary>
        public static string EmailIsDuplicateException {
            get {
                return ResourceManager.GetString("EmailIsDuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی نمیتواند خالی باشد.
        /// </summary>
        public static string FullNameCannotBeEmptyException {
            get {
                return ResourceManager.GetString("FullNameCannotBeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس نمی تواند خالی باشد.
        /// </summary>
        public static string PhoneNumberCannotBeEmptyException {
            get {
                return ResourceManager.GetString("PhoneNumberCannotBeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره تلفن وارد شده صحیح نمی باشد.
        /// </summary>
        public static string PhoneNumberFormatIsInvalidException {
            get {
                return ResourceManager.GetString("PhoneNumberFormatIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مشتری قبلا ثبت شده است.
        /// </summary>
        public static string ThisCustomerAlreadyExistException {
            get {
                return ResourceManager.GetString("ThisCustomerAlreadyExistException", resourceCulture);
            }
        }
    }
}
